import { TodoCardProps } from "./components/TodoCard";

export const todosMock: TodoCardProps[] = [
  {
    title: "Buy groceries",
    description: "Milk, eggs, bread",
    dueDate: "2024-11-20",
    status: "INCOMPLETE",
    priority: "HIGH",
  },
  {
    title: "Walk the dog",
    description: "Evening walk in the park",
    dueDate: "2024-11-21",
    status: "INCOMPLETE",
    priority: "MEDIUM",
  },
  {
    title: "Finish project report",
    description: "Complete the final report for the client",
    dueDate: "2024-11-22",
    status: "INCOMPLETE",
    priority: "HIGH",
  },
  {
    title: "Schedule dentist appointment",
    description: "Book an appointment with Dr. Smith",
    dueDate: "2024-11-23",
    status: "INCOMPLETE",
    priority: "LOW",
  },
  {
    title: "Read a book",
    description: "Read 30 pages of a book",
    dueDate: "2024-11-24",
    status: "COMPLETE",
    priority: "MEDIUM",
  },
  {
    title: "Buy new shoes",
    description: "Get a pair of running shoes",
    dueDate: "2024-11-25",
    status: "INCOMPLETE",
    priority: "LOW",
  },
  {
    title: "Complete coding challenge",
    description: "Finish the algorithm task",
    dueDate: "2024-11-26",
    status: "INCOMPLETE",
    priority: "HIGH",
  },
  {
    title: "Clean the house",
    description: "Dust and vacuum the living room",
    dueDate: "2024-11-27",
    status: "INCOMPLETE",
    priority: "MEDIUM",
  },
  {
    title: "Call mom",
    description: "Catch up with mom on the phone",
    dueDate: "2024-11-28",
    status: "COMPLETE",
    priority: "LOW",
  },
  {
    title: "Go for a run",
    description: "Morning jog for 30 minutes",
    dueDate: "2024-11-29",
    status: "INCOMPLETE",
    priority: "MEDIUM",
  },
  {
    title: "Update resume",
    description: "Add recent work experience and skills",
    dueDate: "2024-11-30",
    status: "INCOMPLETE",
    priority: "MEDIUM",
  },
  {
    title: "Organize desk",
    description: "Tidy up the workspace and file papers",
    dueDate: "2024-12-01",
    status: "COMPLETE",
    priority: "LOW",
  },
  {
    title: "Watch a movie",
    description: "Catch up with a new release",
    dueDate: "2024-12-02",
    status: "COMPLETE",
    priority: "LOW",
  },
  {
    title: "Prepare for presentation",
    description: "Create slides and practice",
    dueDate: "2024-12-03",
    status: "INCOMPLETE",
    priority: "HIGH",
  },
  {
    title: "Buy birthday gift",
    description: "Get a gift for friend's birthday",
    dueDate: "2024-12-04",
    status: "INCOMPLETE",
    priority: "HIGH",
  },
];
